### ISSUE TITLE
언패킹 오류

### ISSUE THREAD

**Issue by vin-spiegel** [SeokguKim/ShortSwordSlicer#1]
![image](https://github.com/SeokguKim/ShortSwordSlicer/assets/75039040/6eae9cff-6d9a-4915-a7ae-485c4dedd2a6)
![image](https://github.com/SeokguKim/ShortSwordSlicer/assets/75039040/7a087a43-2ad9-4cc3-ab68-5a6534381a86)

릴리즈 버전으로 다운 받아서 언패킹 했는데 이렇게 뜨고 있습니다.
폴더 내부에는 파일이 하나도 없네요

**Comment by seokgukim** [comment]
파일명이 한글이거나 하면 윈도우 경로를 제대로 받아오지 못해서 버런 오류가 날 수 있습니다.
영숫자(ASCII 범위)의 파일명으로 변경한 뒤 다시 시도해보세요.

**Comment by vin-spiegel** [comment]
감사합니다. 잘 되네요!
